from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TEST_IMAGE_DIR = PROJECT_ROOT / "img-test"
JPEG_IMAGE_PATH = TEST_IMAGE_DIR / "DSC_0061.JPG"
SECOND_JPEG_IMAGE_PATH = TEST_IMAGE_DIR / "DSC_0050.JPG"
JPEG_IMAGE_PATHS = (JPEG_IMAGE_PATH, SECOND_JPEG_IMAGE_PATH)
